#   ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
#   ¶¶_________________________________________¶¶
#   ¶¶___¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶_________________¶¶
#   ¶¶___¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶_______________¶¶
#   ¶¶_____¶¶¶¶¶_____________¶¶¶¶¶_____________¶¶
#   ¶¶_____¶¶¶¶¶_¶¶¶¶¶¶¶¶¶¶¶__¶¶¶¶_¶¶¶¶________¶¶
#   ¶¶_____¶¶¶¶¶_¶¶¶¶¶¶¶¶¶¶¶¶_¶¶¶¶¶_¶¶¶¶¶______¶¶
#   ¶¶_____¶¶¶¶¶___¶¶¶¶_______¶¶¶¶¶__¶¶¶¶______¶¶
#   ¶¶_____¶¶¶¶¶___¶¶¶¶_______¶¶¶¶¶__¶¶¶¶¶_____¶¶
#   ¶¶_____¶¶¶¶¶___¶¶¶¶_______¶¶¶¶¶__¶¶¶¶¶_____¶¶
#   ¶¶_____¶¶¶¶¶___¶¶¶¶______¶¶¶¶¶¶__¶¶¶¶¶_____¶¶
#   ¶¶_____¶¶¶¶¶___¶¶¶¶_____¶¶¶¶¶¶___¶¶¶¶¶_____¶¶
#   ¶¶_____¶¶¶¶¶___¶¶¶____¶¶¶¶¶¶¶____¶¶¶¶¶_____¶¶
#   ¶¶_____¶¶¶¶¶______¶¶¶¶¶¶¶¶¶_____¶¶¶¶¶______¶¶
#   ¶¶_____¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶_____¶¶¶¶¶¶¶______¶¶
#   ¶¶_____¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶_¶¶¶¶¶¶¶¶________¶¶
#   ¶¶_____¶¶¶¶¶___________¶¶¶_¶¶¶¶¶¶__________¶¶
#   ¶¶_____¶¶¶¶¶___¶¶¶¶¶¶¶¶_¶¶¶__¶¶¶¶__________¶¶
#   ¶¶_____¶¶¶¶¶___¶¶¶¶¶¶¶¶¶_¶¶¶__¶¶¶¶_________¶¶
#   ¶¶_____¶¶¶¶¶___¶¶¶¶______¶¶¶¶__¶¶¶¶________¶¶
#   ¶¶_____¶¶¶¶¶___¶¶¶¶_______¶¶¶¶__¶¶¶¶_______¶¶
#   ¶¶_____¶¶¶¶¶___¶¶¶¶_______¶¶¶¶___¶¶¶_______¶¶
#   ¶¶_____¶¶¶¶¶___¶¶¶¶_______¶¶¶¶___¶¶¶¶______¶¶
#   ¶¶_____¶¶¶¶¶___¶¶¶¶_______¶¶¶¶___¶¶¶¶______¶¶
#   ¶¶_____¶¶¶¶¶¶¶_¶¶¶¶_______¶¶¶¶¶¶_¶¶¶¶______¶¶
#   ¶¶____¶¶¶¶¶¶¶¶_¶¶¶¶______¶¶¶¶¶¶¶_¶¶¶¶______¶¶
#   ¶¶_____________¶¶¶¶¶¶____________¶¶¶¶¶¶____¶¶
#   ¶¶____________¶¶¶¶¶¶¶___________¶¶¶¶¶¶¶____¶¶
#   ¶¶_________________________________________¶¶
#   ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
#author: 尺Ɋ几ᗪㄖ爪卄卂乂
#version: 1.0
#last-update: 3:47 pm (UTC +2) - 08/19/2020 (MM/DD/YEAR)
Locations:
  # For coords string do : x, y, z
  Lobby:
    WorldName: "world"
    coords: "0, 80, 0"

  FirstAC:
    redLoc:
      WorldName: "world"
      coords: "100, 80, 92"
    blueLoc:
      WorldName: "world"
      coords: "150, 80, 20"
    greenLoc:
      WorldName: "world"
      coords: "200, 80, 50"
    yellowLoc:
      WorldName: "world"
      coords: "500, 80, 10"

  SecondAC:


Permissions:
  # Permission to use activity manager commands
  ActivityManager: "challengers.acmanager.use"
  # Permission to get staff chat format
  StaffChatFormat: "challengers.staffchat.use"

Messages:
  # Message when the player hasn't the permission to run a command
  NotAllowed: "&5Erreur » Vous n'avez pas la permission d'éxécuter cette commande."
  # Message when a non player run the command
  NotInstanced: "&5Erreur » Vous devez être un joueur pour pouvoir effectuer cette commande."
  # Message when the player doesn't exists
  NotValid: "&5Erreur » Le joueur specifié n'est pas connecté sur le serveur."
  # Message when the player isn't playing
  NotPlaying: "&5Erreur » Vous devez être un challenger afin d'effectuer cette action."
  # Message when the player is already instanced
  AlreadyPlaying: "&5Erreur » Le joueur &e%player% &4est déjà dans la liste des joueurs."
  # Message when the player is already not playing
  AlreadyNotPlaying: "&5Erreur » Le joueur &e%player% &4n'est déjà pas un challenger."
  # Message when a new player has been added
  NewPlayer: "&2Vous venez d'ajouter le joueur &e%player% à la liste des challengers !"
  # Message to the player when it has been added
  NewPlayerToMessage: "&2Vous venez d'être ajouté à la liste des challengers !"
  # Message when the player has been removed
  RemovedPlayer: "&2Vous venez de retirer &e%player% de la liste des challengers !"
  # Message to the player when it has been removed
  RemovedPlayerToMessage: "&2Vous venez d'être retiré de la liste des challengers !"
  # Message when the game is already running
  AlreadyRunning: "&5Erreur » Une activité est déjà en cours... Pour en forcer l'arrêt veuillez exécuter la commande &e/ac stop. &cPEUT CORROMPRE LE JEU."
  # Message when the game is already not running
  NotRunning: "&5Erreur » Aucune activité n'est démarré."
  # Message when a player has started an activity
  ActivityStarted: "&2Vous venez de démarrer l'activité &e"
  # Message when the activity has been force stopped
  ActivityForceStopped: "&2L'arrêt de l'activité a été forcé » Vous avez été téléporté au lobby"
  # Message to the player who forced stopped the activity
  StoppedActivity: "&2L'arrêt de l'activité a été effectué avec succès !"

  # Message of the old amount of player points
  OldPoints: "&2Nombre de point du joueur %player% » &e%playerpoints% \n&2Nombre de point de la team %teamcolor% %team%: &e%teampoints%"
  #EXCLUDED
  GettingPoints: "&eCalcul du nombre de points..."
  #EXCLUDED
  # Message of the new amount of player points
  NewPoints: "&2Nombre de point du joueur %player% » &e%playerpoints% \n&2Nombre de point de la team %teamcolor% %team%: &e%teampoints%"

  # Player points settings
  AddedPlayerPoints: "&2Vous avez avec succès ajouté %points% points au joueur %teamcolor% %player%"
  RemovedPlayerPoints: "&2Vous avez avec succès supprimé %points% points du joueur %teamcolor% %player%"
  SetPlayerPoints: "&2Vous avez avec succès définis le nombre de point du joueur %teamcolor% %player% à &e%points%"

  # Team points settings
  AddedTeamPoints: "&2Vous avez avec succès ajouté %points% points à l'équipe %teamcolor% %team%"
  RemovedTeamPoints: "&2Vous avez avec succès supprimé %points% points de l'équipe %teamcolor% %team%"
  SetTeamPoints: "&2Vous avez avec succès définis le nombre de point de l'équipe %teamcolor% %team% à &e%points%"

  # Player points message settings
  AddedPlayerPointsToMessage: "&2Vous avez reçu &e%playerpoints% points &2!"
  RemovedPlayerPointsToMessage: "&2Vous avez perdu &e%playerpoints% points &2!"
  SetPlayerPointsToMessage: "&2Votre nombre de point a été défini à &e%playerpoints% points &2!"

  # Team points messages settings
  AddedTeamPointsToMessage: "&2Votre équipe a reçu &e%teampoints% points &2!"
  RemovedTeamPointsToMessage: "&2Votre équipe a perdu &e%teampoints% points &2!"
  SeTeamPointsToMessage: "&2Le nombre de point de votre équipe a été défini à &e%teampoints% points &2!"

  Teams:
    AlreadyInTeam: "&5Erreur » Vous êtes déjà dans l'équipe » %teamcolor%%team%&4."
    TeamIsFull: "&5Erreur » l'équipe » %teamcolor%%team% &4est complète."
    JoinedTheTeam: "&aVous avez rejoint l'équipe » %teamcolor%%team%&4."
    NeedToBeInTeam : "&5Erreur » Vous devez être dans une équipe afin d'effectuer cette action."
    PlayerNeedToBeInTeam : "&5Erreur » Le joueur » %player% doit être dans une équipe pour pouvoir effectuer cette action."

  # Messages for the first Activity
  FirstAC:
    Start: "&aCombattantes, Combattants, Préparez vous, L'épreuve &en°1 &ava débuter !"
    Timer: "&aLa salle des votes se fermera dans &b%timer%"
    # Timer in second, need to be a integer !
    TimerI: 240
    Teleported: "&aVous venez d'être téléporté pour la première épreuve. \nBonne chance !"
    CannotVoteForYourself: "&5Erreur » Vous ne pouvez pas voter pour vous-même"
    VIP:
      VoteVip: "&aVous avez voté pour &e%player%"
      AlreadyVoted: "&5Erreur » Vous avez déjà voté pour un VIP."
      AlreadyFinished: "&5Erreur » La séléction des VIPS finis."
      FinishedVIP: "&aLa salle des votes de VIP est close ! Les choix sont maintenant fait !"
      AnnounceWhoVIP: "&aLe VIP de l'équipe » %teamcolor%%team% est %teamcolor% %player% !"
    BodyGuard:
      AlreadySelected: "&5Erreur » Vous avez déjà séléctionné vos deux gardes du corps."
      Selected: "&aVous avez voté pour %player% en tant qu'un de vos gardes du corps !"
      AlreadySelectedAsBG: "&aVous avez déjà pour %player% en tant qu'un de vos gardes du corps !"
      FinishedBG: "&aLe choix des gardes du corps des VIP est terminé !"
      AnnounceWhoBG: "&aLe %number% garde du corp de l'équipe » %teamcolor%%team% est %teamcolor% %player% !"
      NotSelectingBodyguards: "&5Erreur » La séléction des gardes du corps n'a pas débuté !"
      NotTheVip: "&5Erreur » Vous n'êtes pas le VIP de votre équipe !"


  # Messages for the second activity
  SecondAC:

