name: Challengers
version: 1.0
author: RqndomHax
main: fr.rqndomhax.challengers.core.Core
commands:
  ac:
    aliases: [activity]
    description: Gère les activités
  vip:
    description: Affiche le menu de vote pour un vip
  bg:
    aliases: [bodyguard]
    description: Affiche le menu de vote pour un garde du corps