name: Challengers
version: 1.0
author: RqndomHax
main: fr.rqndomhax.challengers.core.Core
commands:
  ac:
    aliases: [activity]
    description: Gère les activités
  vipselect:
    description: Affiche le menu de vote pour un vip